.PHONY: format

unexport CLANG_FMT        := clang-format
unexport CLANG_FMT_FLAGS  := -i

format:
	$(CLANG_FMT) $(CLANG_FMT_FLAGS) $(PROJECT_SOURCES)
	$(CLANG_FMT) $(CLANG_FMT_FLAGS) $(PROJECT_HEADERS)
	$(CLANG_FMT) $(CLANG_FMT_FLAGS) $(PROJECT_TESTS_SOURCES)

